export { default as Navigation } from './Navigation/Navigation';
export { default as LanguageSelector } from './LanguageSelector/LanguageSelector';
export { default as HeroSection } from './HeroSection/HeroSection';
export { default as AboutSection } from './AboutSection/AboutSection';
export { default as EducationSection } from './EducationSection/EducationSection';
export { default as ProjectsSection } from './ProjectsSection/ProjectsSection';
export { default as ProjectCard } from './ProjectCard/ProjectCard';
export { default as ContactSection } from './ContactSection/ContactSection';
export { default as Footer } from './Footer/Footer';
